import Link from "next/link";
import { ArrowDownRight, ArrowUpRight } from "lucide-react";
import { HeroScene } from "@/components/HeroScene";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";
import { ProjectPortal } from "@/components/ProjectPortal";
import { featuredProjects } from "@/data/projects";

export default function Home() { return <><main><SiteHeader/><section className="hero"><div className="hero-copy"><p className="eyebrow"><span></span> Independent design & frontend partner</p><h1>Interfaces with<br/><em>intent.</em> Built to ship.</h1><p className="hero-intro">White-label UI design and frontend production for digital agencies that need a reliable, detail-focused extension of their team.</p><div className="hero-actions"><Link className="button button-dark" href="/contact">Start a paid pilot <ArrowUpRight size={17}/></Link><Link className="quiet-link" href="#selected-work">Explore selected work <ArrowDownRight size={17}/></Link></div></div><HeroScene/></section>
<section className="statement"><p className="eyebrow">What I bring to the partnership</p><div><h2>Good work is not just a beautiful screen. It is the confidence that the <em>brief, design and build</em> will hold together.</h2><p>For over 16 years, I have helped teams turn ideas into clear, responsive digital experiences—from high-conversion websites to complex product interfaces.</p></div></section>
<section className="transformation"><div className="sticky-label"><p className="eyebrow">From first signal to final surface</p><p>A measured delivery process, without the unnecessary noise.</p></div><div className="transformation-steps"><article><b>01</b><h3>Clarify the brief</h3><p>We identify the goal, the audience and the decisions that actually matter before pixels move.</p></article><article><b>02</b><h3>Shape the system</h3><p>Interface direction, components and responsive behavior become a coherent visual language.</p></article><article><b>03</b><h3>Build with precision</h3><p>Thoughtful frontend implementation turns the direction into a durable client-ready experience.</p></article></div></section>
<section className="selected-work" id="selected-work"><div className="section-heading"><div><p className="eyebrow">A selected body of work</p><h2>Made to be<br/><em>explored.</em></h2></div><Link className="text-link" href="/work">View all work <ArrowUpRight size={18}/></Link></div><div className="portal-grid">{featuredProjects.map((project, index)=><ProjectPortal key={project.slug} project={project} index={index}/>)}</div></section>
<section className="partner-pitch"><div className="pitch-visual"><span>Brief</span><i></i><span>Direction</span><i></i><span>Delivery</span></div><div><p className="eyebrow">A calmer way to expand capacity</p><h2>For agencies who need more hands without adding more complexity.</h2><p>Bring a defined piece of work or keep me in reserve for busy delivery periods. Communication stays clear, the work stays under your brand, and the output is ready for your client.</p><Link className="button button-light" href="/agency-partner">How the partnership works <ArrowUpRight size={17}/></Link></div></section>
<section className="proof"><p className="eyebrow">Built on experience</p><div className="proof-grid"><div><strong>16<span>+</span></strong><p>Years designing and building for the web</p></div><div><strong>UI × FE</strong><p>One partner across interface direction and responsive implementation</p></div><div><strong>Global</strong><p>Asynchronous-friendly collaboration from Lahore, Pakistan</p></div></div></section>
</main><SiteFooter/></> }
